server:
  port: 8080
 
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://dpg-d8f0ugi8qa3s738f9h50-a.ohio-postgres.render.com:5432/librarymanager
    username: admin
    password: 2fovTJwg8WuCSGePI5RQ4Wn830zBmK8w
    driverClassName: org.postgresql.Driver
 
  jpa:
    hibernate:
      ddl-auto: create-drop
 
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgresql.sql